### ISSUE TITLE
VS Code - SQLite: Open Database returns command 'sqlite.explorer.add' not found

### ISSUE THREAD

**Issue by Paulo-JAT** [AlexCovizzi/vscode-sqlite#175] opened 2021-05-18 12:07 UTC
I've installed the SQLite extension on VS Code and when i try to open the database it returns  "command 'sqlite.explorer.add' not found". 

I've tried to right-click on the database to open it and nothing happens.

Maybe i'm missing something, can you help ?

**Comment by Paulo-JAT** [comment] 2021-05-21 08:25
Hi @AlexCovizzi ! 

**OS**
![image](https://user-images.githubusercontent.com/84274767/119106306-1fc54180-ba16-11eb-95df-9c0e25bbb06c.png)

**VS Code**
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by AlexCovizzi** [comment] 2021-05-30 09:51
Hi @Paulo-JAT! Sorry, for looking into this so late, I have another question, do you get some other error before `command 'sqlite.explorer.add' not found`?
The only way I can reproduce this is if an error is thrown during activation, but I am not able to find where it could occur in your case.
If an error occurs in an extension you can check it in more detail by running the command:
`Ctrl + Shift + P` -> `Developer: Show Logs` -> `Extension Host`

**Comment by passionate-zebracorn** [comment] 2021-07-07 17:33
Looks like this got dropped by the originator but I am having the same issue with all the same build details. The command above showing the developer extension logs gave me the output below.
![ext_snip](https://user-images.githubusercontent.com/73192591/124803867-40dae680-df1f-11eb-8bc9-6e19e2810100.png)


I also tried a work around by downloading the vsix from your page and adding the Install .VSIX extension. When I did so I got the below error...

![image](https://user-images.githubusercontent.com/73192591/124804052-7a135680-df1f-11eb-91c8-462c918bd34f.png)

Any help would be greatly appreciated. Thanks!

**Comment by AlexCovizzi** [comment] 2021-07-08 15:56
Hi @passionate-zebracorn, in your case it looks like you have an old version of vscode, I think on version 0.9.0 of the extension I changed the minimum required version of VSCode to 1.30.0.
You should be able to solve this issue by updating your VSCode.

**Comment by passionate-zebracorn** [comment] 2021-07-08 20:15
That was for the win. Thank you for your help. Like a true noob when "check for updates" produced nothing I assumed I was on the most up to date. That was incredibly wrong. Running 1.58.0 and your extension works like a champ. Much appreciated.

**Comment by AlexCovizzi** [comment] 2021-07-12 15:45
Closing this issue since it looks like updating vscode is the solution also for @Paulo-JAT

**Closed by AlexCovizzi** 2021-07-12 15:45 UTC
